default:
  outputs:
    prod:
      type: snowflake
      account: "fdrmidp-pp11878"
      user: "{{ env_var('DBT_PROFILE_USER') }}"
      role: dbt_dev_role
      password: "{{ env_var('DBT_PROFILE_PASSWORD') }}"
      database: dbt_hol_dev
      warehouse: dbt_dev_wh
      schema: public